version: '3.3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgresdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Pass2022!}
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ~/postgres-data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: unless-stopped
