\c stock_db;

DROP TABLE T_STOCK_LOG;
DROP VIEW V_WORKERS_COMMON;
DROP VIEW V_WORKERS_AUTH;
DROP TABLE T_WORKERS;
DROP TABLE IF EXISTS T_SWAPS;
DROP TABLE IF EXISTS T_STOCK;
DROP TABLE IF EXISTS T_DETAILS;
DROP TABLE IF EXISTS T_PRODUCERS;