Server:
        Port: 8002

DB_PRODUCERS:
        DB_NAME: "stock_db"
        DB_USER: "producers_integrator"
        DB_USER_PASSWORD: "producers_integrator"
        DB_HOST: "127.0.0.1"
        DB_PORT: 5432

DB_DETAILS:
        DB_NAME: "stock_db"
        DB_USER: "details_integrator"
        DB_USER_PASSWORD: "details_integrator"
        DB_HOST: "127.0.0.1"
        DB_PORT: 5432