Server:
        Port: 8002

Clients:
        - Authentification

Authentification:
        Host: "127.0.0.1"
        Port: 8003

DB_PRODUCERS:
        DB_NAME: "stock_db"
        DB_USER: "producers_integrator"
        DB_USER_PASSWORD: "producers_integrator"
        DB_HOST: "127.0.0.1"
        DB_PORT: 5432

DB_DETAILS:
        DB_NAME: "stock_db"
        DB_USER: "details_integrator"
        DB_USER_PASSWORD: "details_integrator"
        DB_HOST: "127.0.0.1"
        DB_PORT: 5432

DB_SWAPS:
        DB_NAME: "stock_db"
        DB_USER: "details_integrator"
        DB_USER_PASSWORD: "details_integrator"
        DB_HOST: "127.0.0.1"
        DB_PORT: 5432

DB_STOCK:
        DB_NAME: "stock_db"
        DB_USER: "stock_integrator"
        DB_USER_PASSWORD: "stock_integrator"
        DB_HOST: "127.0.0.1"
        DB_PORT: 5432
