DB_AUTH_POSTGRES:
        DB_NAME: "stock_db"
        DB_USER: "auth_integrator"
        DB_USER_PASSWORD: "auth_integrator"
        DB_HOST: "127.0.0.1"
        DB_PORT: 5432

DB_AUTH_REDIS:
        DB_HOST: "127.0.0.1"
        DB_PORT: 6379