Server:
        Port: 8006

DB_WORKERS:
        DB_NAME: "stock_db"
        DB_USER: "stock_reader"
        DB_USER_PASSWORD: "stock_reader"
        DB_HOST: "127.0.0.1"
        DB_PORT: 5432

DB_AUTH_POSTGRES:
        DB_NAME: "stock_db"
        DB_USER: "stock_reader"
        DB_USER_PASSWORD: "stock_reader"
        DB_HOST: "127.0.0.1"
        DB_PORT: 5432

DB_AUTH_REDIS:
        DB_HOST: "127.0.0.1"
        DB_PORT: 6379

DB_AUTH_SECTION: "DB_AUTH_POSTGRES"

ENCRYPT:
        SALT: "Manchester United"

AUTH:
        MINUTES_TO_EXPIRE: 180
        SECRET_WORD: "Manchester United"
