name: ci build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: maxermu/stock_build_env

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        mkdir build && cd build
        cmake ../src
        make -j4
    - name: which
      run: which g++-10