name: ci build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: maxermu/stock_build_env

    steps:
    - uses: actions/checkout@v2
    - name: pwd
      run: pwd
    - name: build
      run: |
        mkdir build && cd build
        cmake ../src
        make -j12
    - uses: actions/upload-artifact@master
      with:
        name: build-artifact
        path: ./build
  
  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    container: maxermu/stock_build_env

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: build-artifact
        path: ./build

    - name: run_unit_tests
      run: |
        cd build 
        ls -a
        cd details
        ls -a
        cd unit_tests
        ls -a
        chmod +x details_unit_tests
        ./details_unit_tests
