name: ci build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: maxermu/stock_build_env

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: ls -a
    - name: which
      run: which g++-10