name: ci build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: maxermu/stock_build_env

    steps:
    - uses: actions/checkout@v2
    - name: pwd
      run: pwd
    - name: build
      run: |
        mkdir build && cd build
        cmake ../src
      #  make -j4
    - uses: actions/upload-artifact@master
      with:
        name: build-artifact
        path: ./
  
  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    container: maxermu/stock_build_env

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: build-artifact
        path: ./build

    # - name: run_unit_tests
    #   run: ./build/details/unit_tests/details_unit_tests
    - name: ls
      run: |
        cd build
        ls -a
        cd details
        ls -a
